services:
  - type: web
    name: devmetrix-api
    runtime: docker
    dockerfilePath: Dockerfile.fastapi
    healthCheckPath: /
    envVars:
      - key: DATA_PATH
        value: /app/data/cleaned_survey_data.csv

  - type: web
    name: devmetrix-dashboard
    runtime: docker
    dockerfilePath: Dockerfile.streamlit
    envVars:
      - key: BACKEND_URL
        fromService:
          name: devmetrix-api
          type: web
          property: host
